Repository cse110-fa21-group22/cse110-fa21-group22, pull requests merged in 2021-12, with the labels that each got.

#235 remove recipe from ALL lists
  components/RecipeCard.js
  components/UserLocalStorage.js
  scripts/recipe.js
Labels: Back-End

#232 Updated search test
  source/__tests__/end-to-end.test.js
  source/__tests__/favoriteRecipePage.test.js
  source/__tests__/search.test.js
  source/__tests__/simpleFlow.test.js
Labels: Testing

#242 master-favorites hidden
  components/RecipeCard.js
  components/UserLocalStorage.js
  scripts/favorites.js
  scripts/recipe.js
Labels: Front-End, Back-End

#301 Change the email button position
  scripts/recipe.js
  source/__tests__/end-to-end.test.js
  styles/recipe.css
Labels: bug
